### ISSUE TITLE
微信支付下载对账单没完成???

### ISSUE THREAD

**Issue by githubxqz** [Wechat-Group/weixin-java-pay-demo#2]
你好...
wxPayService.downloadBill

String url = this.getPayBaseUrl() + "/pay/downloadbill";
    //TODO 返回的内容可能是文件流，也有可能是xml，需要区分对待
    String responseContent = this.post(url, request.toXML());

    WxPayCommonResult result = WxPayBaseResult.fromXML(responseContent, WxPayCommonResult.class);
    result.checkResult(this);
    //TODO 待实现，暂时无测试帐号，无法调试
    return null;

**Comment by binarywang** [comment]
确实如此，希望有人能帮忙实现一下，非常感谢~

**Comment by binarywang** [comment]
已实现，等待发布最新的sdk
