### ISSUE TITLE
com.github.binarywang.wxpay.bean.request.WxEntPayRequest

### ISSUE THREAD

**Issue by 51Bigod** [Wechat-Group/weixin-java-pay-demo#4]
关于企业付款的实体WxEntPayRequest，其中公众号ID没有set/get方法

**Comment by binarywang** [comment]
公众号ID？是指哪个属性？appid吗？

**Comment by 51Bigod** [comment]
mch_id

**Comment by 51Bigod** [comment]
刚刚写错了，应该是mch_appid

**Comment by 51Bigod** [comment]
还是说你在转XML的时候做了处理，将appid转成了<mch_appid></mch_appid>

**Comment by 51Bigod** [comment]
<xml>
  <nonce_str>1497318711884</nonce_str>
  <sign>EB50F2223A0C2060A599EE867F1A0FA9</sign>
  <mch_appid defined-in="xml">wx0d9ec08cde28f7b6</mch_appid>
  <mchid>1470696702</mchid>
  <partner_trade_no>149731871187459</partner_trade_no>
  <check_name>NO_CHECK</check_name>
  <amount>0</amount>
  <desc>礼物提现</desc>
  <mch_appid>wx0d9ec08cde28f7b6</mch_appid>
</xml>
理解了，谢谢了

**Comment by 51Bigod** [comment]
`<xml>
  <nonce_str>1497318711884</nonce_str>
  <sign>EB50F2223A0C2060A599EE867F1A0FA9</sign>
  <mch_appid defined-in="xml">wx0d9ec08cde28f7b6</mch_appid>
  <mchid>1470696702</mchid>
  <partner_trade_no>149731871187459</partner_trade_no>
  <check_name>NO_CHECK</check_name>
  <amount>0</amount>
  <desc>礼物提现</desc>
  <mch_appid>wx0d9ec08cde28f7b6</mch_appid>
</xml>`理解了，谢谢了

**Comment by 51Bigod** [comment]
`  @Override
  public String getAppid() {
    return this.mchAppid;
  }

  @Override
  public void setAppid(String appid) {
    this.mchAppid = appid;
  }`

**Comment by binarywang** [comment]
也就是说没问题了吧，你应该先关注下是否可以调用成功吧

**Comment by 51Bigod** [comment]
嗯嗯，受教了，谢谢了
