### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ynial** [Wechat-Group/weixin-java-pay-demo#7]
WxPayController.java

    @Override
    @PostMapping("/micropay")
    public WxPayMicropayResult micropay(@RequestBody WxPayMicropayRequest request) throws WxPayException {
        return this.micropay(request);
    }

死循环的bug了 

改成 return this.wxService.micropay(request);

**Comment by binarywang** [comment]
发现错误可以直接提交PR，多谢~
