### ISSUE TITLE
关于POST方法测试

### ISSUE THREAD

**Issue by liuhui0609** [Wechat-Group/weixin-java-pay-demo#8]
下面是我写的部分测试代码，

String uri = "/pay/micropay";
		
Builder bulider = WxPayMicropayRequest.newBuilder();
bulider.outTradeNo("1493279484111-2xxx4");
bulider.body("测试");
bulider.totalFee(1);
bulider.authCode("130355264924095053");
bulider.spbillCreateIp("8.8.8.8");
		
WxPayBaseRequest param = bulider.build();
ObjectMapper mapper = new ObjectMapper();

MvcResult mvcResult = mvc.perform(MockMvcRequestBuilders.post(uri).content(mapper.writeValueAsString(param))
			.contentType(MediaType.APPLICATION_JSON).accept(MediaType.APPLICATION_JSON)).andReturn();

一直返回错误消息。“Can not construct instance of com.github.binarywang.wxpay.bean.request.WxPayMicropayRequest: no suitable constructor found”

请问，这个WxPayMicropayRequest我该如何创建？

**Comment by binarywang** [comment]
demo只是给你演示下如何调用具体的service里的方法，具体你如何创建，可以灵活处理，比如，你可以把参数改成一个个的参数变量，或者自己创建一个vo对象，替换目前的参数对象。

**Comment by binarywang** [comment]
针对这个错误，是因为WxPayMicropayRequest没有实现默认的构造方法，因为本身实现了一个带builder的私有构造方法

**Comment by binarywang** [comment]
报的错误应该是jackson的吧，它可能需要默认构造方法才能生成json

**Comment by liuhui0609** [comment]
您说的是，确实是因为缺少public的构造方法、才造成这个问题。
了解了，我们自己重新写自己的controller。
