### ISSUE TITLE
关于异常

### ISSUE THREAD

**Issue by liuhui0609** [Wechat-Group/weixin-java-pay-demo#9]
在WxPayOrderQueryRequest类中：
throw new IllegalArgumentException("transaction_id 和 out_trade_no 不能同时存在或同时为空，必须二选一");

请问，没有使用WxPayException类进行异常抛出，是基于什么考虑？

**Comment by binarywang** [comment]
这个是因为属于非法参数的问题，就借用了现成的IllegalArgumentException，不过也可以改为新实现的WxPayException

**Comment by liuhui0609** [comment]
BeanUtils类中，关于参数相关的异常，抛出的是WxPayException。
“String msg = "必填字段 " + requiredFields + " 必须提供值";
throw new WxErrorException(WxError.newBuilder().setErrorMsg(msg).build());”

而非“ IllegalArgumentException”，建议保持一致，统一采用WxPayException。
方便外部统一捕获、处理。

**Comment by binarywang** [comment]
那这确实是个问题，后面统一修改下

**Comment by binarywang** [comment]
2.7.7.BETA已修改

**Comment by liuhui0609** [comment]
OK
